#!/usr/bin/env bash
#install and configure new load balancer
apt-get install --no-install-recommends -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get install -y haproxy=2.6.\*
echo "ENABLED=1" > /etc/default/haproxy
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 65298-web-01 35.174.207.85:80 check
   server 65298-web-02 52.204.97.13:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy start
