#!/usr/bin/env bash
#install and configure new load balancer
apt-get install --no-install-recommends -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get install -y haproxy=2.6.\*
fe="frontend main\n\tbind *:80\n\toption forwardfor\n\tdefault_backend webservers"
be="backend webservers\n\tbalance roundrobin\n\tserver web01 35.174.207.85:80 check\n\tserver web02 52.204.97.13:80 check"
file='/etc/haproxy/haproxy.cfg'
echo -e "$fe" >> $file
echo -e "$be" >> $file
echo "ENABLED=1" > /etc/default/haproxy
service haproxy start
