#!/usr/bin/env bash
#this script modifies the /etc/hosts file
cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.*/127.0.0.2\tlocalhost/' ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
