#!/usr/bin/env bash
#configure nginx to use user NGinx instead of root
service nginx stop
#change the listening port for nginx to listen to port 8080
sed -i "s/listen .*/listen *:8080;/" /etc/nginx/sites-available/default
sed -i 's/user .*/user nginx;/' /etc/nginx/sites-available/default
service nginx start
